### ISSUE TITLE
IGNF/FRACTAL-IRGB datasets

### ISSUE THREAD

**Issue by lihc-cz** [CharlesGaydon/CharlesGaydon#1]
Hi, I recently read your paper on FRACTAL dataset and I was wondering if there are any labeled semantic labels in the Fractal-IRGB dataset for 2D images, as I saw you mentioned 2D-3D multi-modal learning. Thank you!

**Comment by CharlesGaydon** [comment]
Hi, thanks for your interest in FRACTAL! No, the [Fractal-IRGB](https://huggingface.co/datasets/IGNF/FRACTAL-IRGB) is provided without any 2D labels. Multi-modal learning could be performed with supervision on the 3D labels only, using the images as additional signal to complement the point clouds (intuition here is that something that is hard to see in 3d might be obvious in 2d). I honestly don't know for sure that it would be useful, I'd have to know more about your use case.

There are pretrained models out there to process IRGB aerial images, e.g. [FLAIR-INC_rgbie_15cl_resnet34-unet](https://huggingface.co/IGNF/FLAIR-INC_rgbie_15cl_resnet34-unet).
